# Generated by Django 5.0.1 on 2024-01-29 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourtCases',
            fields=[
                ('court_case_id', models.IntegerField(primary_key=True, serialize=False)),
                ('court_case_number', models.CharField(max_length=30)),
                ('court_case_name', models.CharField(max_length=30)),
                ('court_case_type', models.CharField(max_length=30)),
                ('court_case_date', models.DateField()),
                ('court_case_time', models.CharField(max_length=30)),
                ('court_case_location', models.CharField(max_length=30)),
                ('court_case_description', models.CharField(max_length=30)),
                ('court_case_parties', models.CharField(max_length=30)),
                ('court_case_judge', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director_id', models.IntegerField(primary_key=True, serialize=False)),
                ('director_first_name', models.CharField(max_length=30)),
                ('director_last_name', models.CharField(max_length=30)),
                ('director_address', models.CharField(max_length=30)),
                ('director_phone_number', models.CharField(max_length=30)),
                ('director_email', models.CharField(max_length=30)),
                ('director_date_of_birth', models.DateField()),
                ('director_national_id', models.CharField(max_length=30)),
                ('director_passport_number', models.CharField(max_length=30)),
                ('director_vehicle_registration_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('next_of_kin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('next_of_kin_phone_number', models.CharField(max_length=30)),
                ('next_of_kin_email', models.CharField(max_length=30)),
                ('next_of_kin_address', models.CharField(max_length=30)),
                ('next_of_kin_relationship', models.CharField(max_length=30)),
                ('next_of_kin_date_of_birth', models.DateField()),
                ('next_of_kin_occupation', models.CharField(max_length=30)),
                ('next_of_kin_id_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousTransactions',
            fields=[
                ('previous_transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('previous_transaction_date', models.DateField()),
                ('previous_transaction_time', models.CharField(max_length=30)),
                ('previous_transaction_amount', models.CharField(max_length=30)),
                ('previous_transaction_description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CriminalRecord',
            fields=[
                ('criminal_record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('criminal_record_description', models.CharField(max_length=30)),
                ('criminal_record_date', models.DateField()),
                ('criminal_record_time', models.CharField(max_length=30)),
                ('criminal_record_location', models.CharField(max_length=30)),
                ('criminal_record_type', models.CharField(max_length=30)),
                ('criminal_record_court_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courtcases')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(max_length=30)),
                ('id_image', models.ImageField(upload_to='images/')),
                ('passport_number', models.CharField(max_length=30)),
                ('date_of_employment', models.DateField()),
                ('position', models.CharField(max_length=30)),
                ('cv', models.FileField(upload_to='files/')),
                ('vehicle_registration_number', models.CharField(max_length=30)),
                ('court_cases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courtcases')),
                ('criminal_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.criminalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentRecord',
            fields=[
                ('employment_record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employment_record_date', models.DateField()),
                ('employment_record_time', models.CharField(max_length=30)),
                ('employment_record_description', models.CharField(max_length=30)),
                ('employment_record_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employmentrecord'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=30)),
                ('company_address', models.CharField(max_length=30)),
                ('company_phone_number', models.CharField(max_length=30)),
                ('company_email', models.CharField(max_length=30)),
                ('company_date_of_incorporation', models.DateField()),
                ('company_registration_number', models.CharField(max_length=30)),
                ('company_court_cases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courtcases')),
                ('company_director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.director')),
                ('company_employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('company_next_of_kin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nextofkin')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_first_name', models.CharField(max_length=30)),
                ('customer_last_name', models.CharField(max_length=30)),
                ('customer_address', models.CharField(max_length=30)),
                ('customer_phone_number', models.CharField(max_length=30)),
                ('customer_email', models.CharField(max_length=30)),
                ('customer_date_of_birth', models.DateField()),
                ('customer_national_id', models.CharField(max_length=30)),
                ('customer_passport_number', models.CharField(max_length=30)),
                ('customer_vehicle_registration_number', models.CharField(max_length=30)),
                ('court_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courtcases')),
                ('customer_criminal_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.criminalrecord')),
                ('customer_previous_transactions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.previoustransactions')),
            ],
        ),
    ]
