# Generated by Django 5.0.1 on 2025-09-19 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["company_name"]},
        ),
        migrations.AlterModelOptions(
            name="courtcases",
            options={"ordering": ["-court_case_date", "court_case_number"]},
        ),
        migrations.AlterModelOptions(
            name="criminalrecord",
            options={"ordering": ["-criminal_record_date", "criminal_record_id"]},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["customer_last_name", "customer_first_name"]},
        ),
        migrations.AlterModelOptions(
            name="director",
            options={"ordering": ["director_last_name", "director_first_name"]},
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.AlterModelOptions(
            name="employmentrecord",
            options={"ordering": ["-employment_record_date", "employment_record_id"]},
        ),
        migrations.AlterModelOptions(
            name="nextofkin",
            options={"ordering": ["next_of_kin_relationship", "next_of_kin_id_number"]},
        ),
        migrations.AlterModelOptions(
            name="previoustransactions",
            options={
                "ordering": ["-previous_transaction_date", "previous_transaction_id"]
            },
        ),
        migrations.RemoveField(
            model_name="company",
            name="company_court_cases",
        ),
        migrations.RemoveField(
            model_name="company",
            name="company_director",
        ),
        migrations.RemoveField(
            model_name="company",
            name="company_employees",
        ),
        migrations.RemoveField(
            model_name="company",
            name="company_next_of_kin",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="court_case",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="customer_criminal_record",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="customer_previous_transactions",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="criminal_record",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="employment_record",
        ),
        migrations.AddField(
            model_name="company",
            name="court_cases",
            field=models.ManyToManyField(
                blank=True,
                help_text="Log relevant court cases for this company.",
                related_name="companies",
                to="core.courtcases",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="directors",
            field=models.ManyToManyField(
                blank=True,
                help_text="Associate directors responsible for this company.",
                related_name="companies",
                to="core.director",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="employees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Attach employees working for this company.",
                related_name="companies",
                to="core.employee",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="next_of_kin",
            field=models.ManyToManyField(
                blank=True,
                help_text="Reference next of kin contacts for company stakeholders.",
                related_name="companies",
                to="core.nextofkin",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="court_cases",
            field=models.ManyToManyField(
                blank=True,
                help_text="Attach any court cases involving this customer.",
                related_name="customers",
                to="core.courtcases",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="criminal_records",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link background screening findings to this customer.",
                related_name="customers",
                to="core.criminalrecord",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="previous_transactions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Associate historical transactions for this customer.",
                related_name="customers",
                to="core.previoustransactions",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="criminal_records",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link any criminal records associated with this employee.",
                related_name="employees",
                to="core.criminalrecord",
            ),
        ),
        migrations.AlterField(
            model_name="criminalrecord",
            name="criminal_record_court_case",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional reference to the court case linked to this record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="criminal_records",
                to="core.courtcases",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_passport_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_vehicle_registration_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="director",
            name="director_passport_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="director",
            name="director_vehicle_registration_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.RemoveField(
            model_name="employee",
            name="court_cases",
        ),
        migrations.AlterField(
            model_name="employee",
            name="cv",
            field=models.FileField(blank=True, null=True, upload_to="files/"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="id_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="passport_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="employee",
            name="vehicle_registration_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="employmentrecord",
            name="employment_record_employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employment_records",
                to="core.employee",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="court_cases",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select any court cases that are relevant to this employee.",
                related_name="employees",
                to="core.courtcases",
            ),
        ),
    ]
